#include "gensnd.h"

#include <math.h>
#include <stdio.h>

void gensine(float frequency, float sampleRate, float duration) {
    float outputSamples = sampleRate * duration;
    float samplesPerCycle = sampleRate / frequency;
    //output a sample every:
    float ouputInterval = (2 * M_PI) / samplesPerCycle;

    float radians;
    int i = 0;
    for (radians = 0; radians < 2 * M_PI; i += outputInterval) {
        printf("Print no %d: %lf\n", i, sin(radians));
        i++;
    }

    //Outputs a sine wave at a specified frequency using
    //samplerate in hertz  for a time duration in seconds.

    //Floating point numbers between -1 and 1, one number per
    //output line. writes to standard out.
}

void dualtone(char key) {
    //outputs the tones that are generated by the keypress
}

void silence(float sampleRate, float duration) {
    //sounds samples that create silence
}
